### ISSUE TITLE
I love it :) -- Make it more pytest-like :P

### ISSUE THREAD

**Issue by prologic** [dudadornelles/psychic#5]
As per title; See: [pytest](https://pypi.python.org/pypi/pytest) -- In fact; why not write a pytest plugin for this? :)

**Comment by dudadornelles** [comment]
Hey! Can you give me more details (maybe an example) on what change you'd
like to see?

**Comment by prologic** [comment]
I was just thinking "out  loud"; wouldn't ie be great if this was ap uy-test plugin :)
